name: Build and Push Docker Image
on:
  push:
    branches:
      - master
jobs:
  push-and-deploy:
    runs-on: ubuntu-latest
    name: Docker build and push to Registry
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the SHA resumed
        env:
          GITHUB_SHA: ${{ github.sha }}
        id: get_commit
        run: echo ::set-output name=COMMIT::$(echo $GITHUB_SHA | rev | cut -c34- | rev)

      - name: Build and push image
        env:
          IMAGE_TAG: go-api-${{ steps.get_commit.outputs.COMMIT }}-prd
        run: |
          docker build -t go-api .
          docker tag go-api:latest registry.codenoobs.xyz/cvfuhr/go-api:$IMAGE_TAG
          docker push registry.codenoobs.xyz/cvfuhr/go-api:$IMAGE_TAG