name: Build and Push Docker Image
on:
  push:
    branches:
      - master
jobs:
  push-and-deploy:
    runs-on: ubuntu-latest
    name: Docker build and push to Registry
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push image
        run: |
          docker build -t go-api .
          docker image tag go-api registry.codenoobs.xyz/cvfuhr/go-api
          docker push registry.codenoobs.xyz/cvfuhr/go-api