apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api
        image: registry.codenoobs.xyz/cvfuhr/go-api:latest
        ports:
        - containerPort: 80